"""empty message

Revision ID: 16b81c8b6dc3
Revises: 9b1abdd4d2a6
Create Date: 2019-10-20 10:35:23.434149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16b81c8b6dc3'
down_revision = '9b1abdd4d2a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audi_ibfk_1', 'audi', type_='foreignkey')
    op.drop_column('audi', 'slot_id')
    op.add_column('slot', sa.Column('audi_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'slot', 'audi', ['audi_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.drop_column('slot', 'audi_id')
    op.add_column('audi', sa.Column('slot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('audi_ibfk_1', 'audi', 'slot', ['slot_id'], ['id'])
    # ### end Alembic commands ###
