"""empty message

Revision ID: 203a8f9ae17a
Revises: 34caafdbe73a
Create Date: 2019-10-08 10:02:22.589738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203a8f9ae17a'
down_revision = '34caafdbe73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('released_on', sa.DateTime(), nullable=True),
    sa.Column('user_ratings', sa.Float(), nullable=True),
    sa.Column('cast', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('languages', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theatre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('audi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audi_name', sa.String(length=20), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('theatre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatre.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('seat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('row', sa.String(length=1), nullable=False),
    sa.Column('column', sa.String(length=1), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('seat_type', sa.String(length=10), nullable=True),
    sa.Column('seat_no', sa.String(length=5), nullable=True),
    sa.Column('seat_price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('audi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audi_id'], ['audi.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat')
    op.drop_table('audi')
    op.drop_table('theatre')
    op.drop_table('movie')
    # ### end Alembic commands ###
