"""empty message

Revision ID: 34caafdbe73a
Revises: 8eca37719119
Create Date: 2019-09-30 21:13:34.468589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34caafdbe73a'
down_revision = '8eca37719119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
