"""empty message

Revision ID: 5ad50daed834
Revises: 
Create Date: 2019-10-20 08:45:10.832768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad50daed834'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('showing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.id'], ),
    sa.ForeignKeyConstraint(['showing_id'], ['showing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seat_id', 'showing_id', name='ticket')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
