"""empty message

Revision ID: 86beae9323e1
Revises: 16b81c8b6dc3
Create Date: 2019-10-20 21:53:46.103486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86beae9323e1'
down_revision = '16b81c8b6dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('seat', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('reservation', 'status')
    # ### end Alembic commands ###
