"""empty message

Revision ID: 8eca37719119
Revises: adef2374870e
Create Date: 2019-09-29 21:37:48.153238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eca37719119'
down_revision = 'adef2374870e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('registered_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'registered_on')
    # ### end Alembic commands ###
